# Generated by Django 3.2.8 on 2021-10-20 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('nome', models.CharField(default='', max_length=70)),
                ('carro', models.CharField(default='', max_length=200)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
