# Generated by Django 3.0.14 on 2021-11-25 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('labBd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id_agendamento', models.AutoField(primary_key=True, serialize=False)),
                ('horario_agendamento', models.DateTimeField()),
                ('data_partida', models.DateField()),
                ('horario_partida', models.TimeField()),
                ('atraso_aceitavel', models.IntegerField()),
                ('adiantam_aceitavel', models.IntegerField()),
                ('ativo', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'agendamento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id_match', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': '_match',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OfertaDeCarona',
            fields=[
                ('id_oferta_de_carona', models.AutoField(primary_key=True, serialize=False)),
                ('data_partida', models.DateField()),
                ('horario_partida', models.TimeField()),
                ('vagas_ofertadas', models.IntegerField()),
                ('vagas_disponiveis', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'oferta_de_carona',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Passageiro',
            fields=[
                ('cpf', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('nota_media', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'passageiro',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ponto',
            fields=[
                ('id_ponto', models.AutoField(primary_key=True, serialize=False)),
                ('latitude', models.IntegerField()),
                ('longitude', models.IntegerField()),
                ('cep', models.CharField(max_length=9)),
                ('num', models.IntegerField()),
                ('logradouro', models.CharField(max_length=50)),
                ('ponto_referencia', models.CharField(blank=True, max_length=100, null=True)),
                ('nome', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'ponto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Possui',
            fields=[
                ('id_possui', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'possui',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id_reserva', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'reserva',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('primeiro_nome', models.CharField(max_length=50)),
                ('sobrenome', models.CharField(max_length=50)),
                ('login', models.CharField(max_length=50)),
                ('dominio', models.CharField(max_length=50)),
                ('data_nasc', models.DateField()),
                ('num', models.IntegerField()),
                ('logradouro', models.CharField(max_length=50)),
                ('cep', models.CharField(max_length=9)),
                ('ddd1', models.IntegerField()),
                ('prefixo1', models.IntegerField()),
                ('num1', models.IntegerField()),
                ('ddd2', models.IntegerField(blank=True, null=True)),
                ('prefixo2', models.IntegerField(blank=True, null=True)),
                ('num2', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('placa', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('modelo', models.CharField(max_length=255)),
                ('n_assentos', models.IntegerField()),
                ('cor', models.CharField(max_length=50)),
                ('ano', models.IntegerField()),
            ],
            options={
                'db_table': 'veiculo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Carona',
            fields=[
                ('id_reserva', models.OneToOneField(db_column='id_reserva', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='labBd.Reserva')),
                ('horario_saida', models.TimeField()),
                ('horario_chegada', models.TimeField()),
                ('avaliacao_motorista', models.TextField(blank=True, null=True)),
                ('avaliacao_passageiro', models.TextField(blank=True, null=True)),
                ('nota_passageiro', models.IntegerField(blank=True, null=True)),
                ('nota_motorista', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'carona',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('numero_cnh', models.IntegerField()),
                ('data_validade_cnh', models.DateField()),
                ('id_usuario', models.OneToOneField(db_column='id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='labBd.Usuario')),
                ('nota_media', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'motorista',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PassaPor',
            fields=[
                ('id_oferta_de_carona', models.OneToOneField(db_column='id_oferta_de_carona', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='labBd.OfertaDeCarona')),
                ('ponto_final', models.BooleanField()),
                ('ponto_inicial', models.BooleanField()),
            ],
            options={
                'db_table': 'passa_por',
                'managed': False,
            },
        ),
    ]
